/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sasdutta.mimeparsing;

import org.apache.james.mime4j.MimeException;

import javax.json.JsonObject;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) {
        Path path = Paths.get(args[0]);
        run(path);
    }

    private static void run(Path path) {
        try (InputStream input = new BufferedInputStream(Files.newInputStream(path))) {
            MimeParser mimeParser = new MimeParser();
            JsonObject json = mimeParser.parse(input);

            System.out.println(json.toString());
        } catch (IOException ex) {
            System.err.println("Failed to read file " + path.toString() + " " + ex.getMessage());
            ex.printStackTrace();
        } catch (MimeException ex) {
            System.err.println("Failed to parse mime file " + ex.getMessage());
            ex.printStackTrace();
        }
    }
}
